version: "3.6"

volumes:
  jupyter_data:
    name: jupyter_data
  jupyter_work:
    name: jupyter_work

services:
  jupyter:
    build: .
    container_name: jupyter
    volumes:
      - jupyter_data:/code
      - jupyter_work:/home/docker_worker/work
#      - ./config/jupiter_notebook_config.py:/root/.jupyter/jupyter_notebook_config.py
    restart: always
    env_file:
      - env
    ports:
      - "8888:8888"