version: "3.6"

volumes:
  jupyter_data:
    name: jupyter_data
  jupyter_config:
    name: jupyter_config
  jupyter_runtime:
    name: jupyter_runtime

services:
  jupyter_lab:
    build: .
    container_name: jupyter_lab
    volumes:
      - jupyter_data:/code
      - jupyter_config:/root/.jupyter
      - jupyter_runtime:/root/.local/share/jupyter/runtime

    ports:
      - "8888:8888"