version: "3.9"

volumes:
  jupiter_data:
    name: jupiter_data
  jupyter_config:
    name: jupyter_config
  jupyter_runtime:
    name: jupyter_runtime

services:
  jupyter_lab:
    build: .
    container_name: jupyter_lab
    volumes:
      - jupiter_data:/code
      - jupyter_config:/root/.jupyter
      - jupyter_runtime:/root/.local/share/jupyter/runtime

    ports:
      - "8888:8888"
    env_file:
      - .env
    entrypoint: [ "jupyter", "lab","--ip=0.0.0.0","--allow-root", "--NotebookApp.token=$JUPYTER_LAB_GATEWAY_HTTP_TOKEN","--NotebookApp.password=''", "--collaborative" ]