version: "3.9"

volumes:
  jupyter_data:
    name: jupyter_data
  jupyter_config:
    name: jupyter_config
  jupyter_runtime:
    name: jupyter_runtime

services:
  jupyter_lab:
    build:
      dockerfile: Dockerfile-cuda
      context: .
      shm_size: '32gb'
    container_name: jupyter_lab
    restart: always
    shm_size: '32gb'
#    ulimits:
#      memlock: -1
#      stack: 67108864
    environment:
      NCCL_DEBUG: INFO
    volumes:
      - jupyter_data:/code
      - jupyter_config:/root/.jupyter
      - jupyter_runtime:/root/.local/share/jupyter/runtime
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    ports:
      - "8888:8888"